### ISSUE TITLE
Full HMR for `.liquid` files

### ISSUE THREAD

**Issue by felixmosh** [3daddict/themekit-webpack#24]
I'm opening this issue in order to make an organized place for the idea described [here](https://github.com/3daddict/themekit-webpack/pull/19#issuecomment-728775874).

The idea is divided into several phases:
#### 1.  HMR of native html
1. Create a dev only entry point which will load all `.liquid` files and pass them when ever they change as a **string**
2. Wrap each file with a start & end unique html comment
3. When an hot update comes replace the HTML between the special comments
#### 2. Manipulate `.liquide` files locally
1. Add support for Shopify only tags such as (`schema`, `section` etc... ) - probably will require some PRs to https://github.com/harttle/liquidjs-section-tags
2. Manipulate `{{ 'bundle.x.js' | asset_url | script_tags }}` & `{{ 'bundle.x.css' | asset_url | stylesheet_tags }}` the same way it is handled in the [CopyAssets task](https://github.com/3daddict/themekit-webpack/blob/master/webpack.config.js#L112)
3. Prefetch store data to provide it to local `.liquid` renders

I've finished phase 1 🎊,
![wFIbPrvOgJ](https://user-images.githubusercontent.com/9304194/99531308-34fbdd80-29ab-11eb-93d0-1744d3a340e5.gif)

In this screenshot, you can see that whenever I edit `message.liquid` it hot replaced in the DOM without page reload!
As you can see it has un-processed `liquid` tags (Phase 2)

**Comment by felixmosh** [comment]
@3daddict , not related to this issue, why do I get this error: ```Liquid error: Error in tag 'section' - 'footer' is not a valid section type```? (it was like that from the starts...)

**Comment by 3daddict** [comment]
> @3daddict , not related to this issue, why do I get this error: `Liquid error: Error in tag 'section' - 'footer' is not a valid section type`? (it was like that from the starts...)

@felixmosh where are you seeing the liquid error? How can I replicate?
