### ISSUE TITLE
Liquid error: Error in tag 'section' - 'footer' is not a valid section type

### ISSUE THREAD

**Issue by felixmosh** [3daddict/themekit-webpack#25]
I'm getting this error on the page it self (start & build) and in the terminal I see that `themekit` writes
```shell
[development] (sections/footer.liquid) New schema is incompatible with the current setting value. Invalid type value for block 'footer-0'. Type must be defined in schema.New schema is incompatible with the current setting value. Invalid type value for block 'footer-1'. Type must be defined in schema
```

In order to reproduce:
git clone https://github.com/3daddict/themekit-webpack/tree/d8310957336c83d3d6a61db7ecf52db644dc3bc2 (this hash is before all the changes in the infra)
add my shopify credentials to `config.yaml` 
yarn install && yarn start

![image](https://user-images.githubusercontent.com/9304194/99500360-f0f4e280-2982-11eb-8154-4eb50d2c6739.png)

**Comment by felixmosh** [comment]
Ha, I've solved it

I've started from a clone of some default template, since `config/settings_data.json` is not uploaded from local env, there was a mismatch.

All I did is to re-upload my current `config/settings_data.json` file.

**Comment by 3daddict** [comment]
Oh yeah, I should have mentioned that. Might be a good note to add in the readme!
Thanks for flagging @felixmosh
