### ISSUE TITLE
Template type 'reset_password' does not support liquid templates

### ISSUE THREAD

**Issue by soheimam** [3daddict/themekit-webpack#48]
Hey team,
Thanks for the hard work this is a great project.

**Description**
After I install all node modules by running `yarn install` and then run `yarn deploy`, i receive an error in the command line `Template type 'reset_password' does not support liquid templates`, I receive this error for all files within the customer subdirectory of the template folder.  

**Environment**
Which environment does the bug exist in?
This error persists in both deploy and watch commands.

**Steps to Reproduce**
Start new project
Install dependencies
Run 'yarn deploy' or 'yarn watch'

**Troubleshooting**
- On first deploy I commented out the ignore files.
- Deleted and reinstalled node modules
- Manually updated settings_data.json
- Moved liquid files in the customers subdirectory of the templates folder, to the template directory level. Removed previous dist  folder and re-deployed.

**Comment by 3daddict** [comment]
Hey @soheimam thanks for checking out this project and creating an issue. I wasn't able to replicate the error.
What version of yarn are you running? Does this issue happen with npm also?
I have yarn version `1.22.5`
I was able to run `yarn install` on a fresh clone and `yarn deploy` without errors.
<img width="761" alt="Screen Shot 2021-01-20 at 6 26 04 PM" src="https://user-images.githubusercontent.com/29803478/105272707-c2e07a00-5b4e-11eb-9ee8-174eb0d6d015.png">

Try updating your yarn version and see if the issue still happens.

**Comment by malcolmb** [comment]
I found this thread while searching for the exact string "does not support liquid templates" as I just started receiving the message after updating node, themekit, and a few other packages. In my case I had "collections-unmodified.liquid" template which I've had for years that it was choking on. I changed the "-" to a "." and it started working again. Having dug into what changed, and likely won't, but figured I'd leave this in case someone else has the same issue.

**Comment by 3daddict** [comment]
Thanks @malcolmb something changed for sure which I haven't been able to identify yet. I had a similar issue with some legacy files from the app Product Filter & Search. I'll poke around some more to see if I can dig up something for future best practice. I suspect it's tied to an update with Node, ThemeKit, or Package Managers.

**Comment by 3daddict** [comment]
@soheimam I see what you mean now when running the dev server. `Template type 'account' does not support liquid templates` I'll work to bring in updated starter files, to see if we can resolve these.

![Screen Shot 2021-01-25 at 9 36 57 PM](https://user-images.githubusercontent.com/29803478/105804792-84cfc580-5f55-11eb-9aa9-d243276856ab.png)

**Comment by 3daddict** [comment]
@soheimam thanks for reporting this issue. I found the problem and it was with the CopyPlugin. It was sending all files to the templates folder. I have now fixed it to send files to templates/customers which has the correct folder structure for Shopify.
You can see PR: [#54](https://github.com/3daddict/themekit-webpack/pull/54/files) for more info.
