### ISSUE TITLE
Production Build Scripts localhost root dir

### ISSUE THREAD

**Issue by 3daddict** [3daddict/themekit-webpack#55]
When running `yarn deploy` assets are still pulling from `localhost`
I am not sure of the files are changing during production build scripts.
<img width="753" alt="Screen Shot 2021-02-02 at 7 09 24 PM" src="https://user-images.githubusercontent.com/29803478/106692968-5de34600-658a-11eb-90c4-c960017f28ca.png">
When I try to load a theme preview after running `yarn deploy` it looks like it's still looking for assets in the localhost root?
<img width="764" alt="Screen Shot 2021-02-02 at 7 12 33 PM" src="https://user-images.githubusercontent.com/29803478/106693121-a13db480-658a-11eb-8b7d-b012f96b5c6c.png">

**Comment by 3daddict** [comment]
@felixmosh if you have a minute can you try running `yarn deploy` and let me know if you see the same issue?
I am not sure if there is a problem with the production config or if this is an issue with my cert on this macbook.

**Comment by felixmosh** [comment]
Will check it asap

**Comment by 3daddict** [comment]
Thanks, no rush I'm sure it's something I broke with the webpack configs or is local to me. I just can't seem to find it.
