### ISSUE TITLE
Webpack serve issue

### ISSUE THREAD

**Issue by craigjamesdobson** [3daddict/themekit-webpack#59]
Hey,

I am getting an issue when trying to start up the dev server. The deploy works fine so im assuming it must be to do with the dev server.

Running it on W10 with node v12.21.0.

Not sure if im missing something really obvious here. You mention node v14 will it not work on older versions? Sorry its vague, this is all I've got to go on.

**Comment by 3daddict** [comment]
Hey @craigjamesdobson ,
In macOS, I switched to `v12.21.0`, installed dependencies, and executed `yarn start`.
Everything seemed to work and webpack compiled successfully opening the browser and starting the dev server.
It might be worth trying with node v14. Send some info here on the issue you are seeing and I'll check it out.

**Comment by craigjamesdobson** [comment]
Switching to node v14 didn't work unfortunately. Its not a long term solution either as I need to be on v12 for some legacy projects. I know I can install nvm for windows but that has caused issues when trying to point paths to the .exe.

Here is the debug.log not sure if its any use. Would love to get this sorted as I very much want to give this a go as it looks fantastic and exactly what I need.

[2021-03-12T11_35_00_049Z-debug.log](https://github.com/3daddict/themekit-webpack/files/6129858/2021-03-12T11_35_00_049Z-debug.log)

**Comment by 3daddict** [comment]
Thanks @craigjamesdobson I see what you mean with the lack of error response detail from the log.
@felixmosh any idea why `themekit-webpack@1.0.0~start: Failed to exec start script` from the log file above?

**Comment by craigjamesdobson** [comment]
Im sure its something I've missed and it will be a simple answer just a pain to pinpoint what's going on. I tried debugging the `webpack.dev.js` file and it seemed to be an issue within the `WebpackShellPlugin` specifically the `onBuildStart` but im not really that much of an expert on Webpack so I could be wrong.

**Comment by felixmosh** [comment]
I'm not sure what can cause this issue  on Windows machines (i don't have a pc)

**Comment by felixmosh** [comment]
I've reviewed the code, looks like we are using linux only shell scripts,

```shell
'echo -- Webpack build started 🛠',
'shopify-themekit watch --env=development',
```
echo probably won't work on windows machines

**Comment by 3daddict** [comment]
Thanks @felixmosh, nice find!!
@craigjamesdobson have you tried something like [cygwin](http://www.cygwin.com/) or the [Linux Bash Shell on Windows 10](https://itsfoss.com/install-bash-on-windows/).
Let me know if any of those work or you find another solution and I'll update the readme.

**Comment by ws-craig** [comment]
@3daddict @felixmosh Thanks for looking into this guys. I tried removing the echo commands and it was still failing and I had a play with the Linux Bash Shell but to be honest I wasn't 100% what I was doing! 

I did a bit more digging and I found [this](https://github.com/s00d/webpack-shell-plugin-next/issues/28) issue on the repo of `webpackShellPlugin` so I guess it could be an issue with the plugin.

**Comment by craigjamesdobson** [comment]
@3daddict The author of that plugin has released an update to `2.2.2` and that has fixed the issue. So it wasn't any of the commands just a simple bug with the plugin! 🎉

I will do a PR with the upgrade to the plugin.

**Comment by 3daddict** [comment]
Thanks @craigjamesdobson I'll review the PR and merge once I have time and create the release. Let me know how the development in the repo goes for you. Happy to hear some feedback!!

**Comment by craigjamesdobson** [comment]
No problem. Glad I was able to sort it as I really wanted to use this project. Thanks for your hard work with it.
