### ISSUE TITLE
localhost wont start

### ISSUE THREAD

**Issue by Michael-Reich** [3daddict/themekit-webpack#65]
Hi, I installed all stuff corretly and wanted to start the dev server, but it wont build till the end.

![Bildschirmfoto 2021-07-01 um 23 38 57](https://user-images.githubusercontent.com/10381330/124192526-b846eb00-dac5-11eb-8c99-e04ce9851393.png)

**Comment by 3daddict** [comment]
Hey @Michael-Reich ,
What version of NodeJS and OS are you running?
Have you installed CLean-CSS CLI?

**Comment by Michael-Reich** [comment]
I use n for node management and tried it with v14 and v12. Same result.

Not yet I try to install it

**Comment by 3daddict** [comment]
I just tried it on node `v14.8.0` with nvm on a fresh clone with macOS and there were no issues to npm or yarn build and start.
Does yarn build work for you?
Are you on Win10?
Maybe it's related to this #59 issue and we need to bump a version.

**Comment by Michael-Reich** [comment]
Nope not working on Windows. Mac 11.4 Big Sur.

Yarn also not working, was also my first guess. How can I provide more information?

**Comment by 3daddict** [comment]
Hey @Michael-Reich I finally had a chance to sit down and study your error code.
It looks like in NodeJS, Axios no longer allows async functions without a catch block.
Can you please try this branch #66 and let me know if this solves the issue or shoots a different error?

**Comment by 3daddict** [comment]
@Michael-Reich let me know if you had a chance to test this, hopefully that'll fix the issue.

**Comment by 3daddict** [comment]
🤞 #66 fixed this
