### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by 3daddict** [3daddict/themekit-webpack#7]
Need to figure out how to get hot-reloading working with current configuration. I am thinking this would be done in the **WebpackShellPluginNext** near the end of the **webpack.config.js** I just haven't found the right way to get it to work.

**Comment by felixmosh** [comment]
What kind of HMR do you need? styles?

**Comment by 3daddict** [comment]
Hey @felixmosh thanks for helping out.
The immediate issue I am looking for is when we are working in development mode we look for a file change on .liquid files and then re-run the scripts.
- build tailwindcss
- build webpack
- deploy changed files to theme
- watch for changes

**Comment by felixmosh** [comment]
I've managed to start a dev env with preview of the template on Shopify.
I see that if i change . liquid file, it won't re upload it.
Is it part of the HMR task?

**Comment by 3daddict** [comment]
Correct @felixmosh it would be great to watch for changes on `.liquid` files and re-upload the changed file as part of the HMR task.

**Comment by 3daddict** [comment]
This has been fixed #19
